### List all activities
GET http://localhost:8080/activity/list

### List activities with date range
GET http://localhost:8080/activity/list?from=2026-01-01T00:00:00Z&to=2026-01-31T23:59:59Z

### List activities for specific project
GET http://localhost:8080/activity/list?project=TOCK

### List only running activities
GET http://localhost:8080/activity/list?running=true

### List activities with multiple filters
GET http://localhost:8080/activity/list?from=2026-01-31T00:00:00Z&to=2026-01-31T23:59:59Z&project=TOCK
